### ISSUE TITLE
Box tutorial data not accessible with personal account

### ISSUE THREAD

**Issue by rkayjay** [hakyimlab/PredictDB-Tutorial#2]
Is there a publicly available repository for accessing the data used for the tutorial? I am unable to access it using a personal Box account.

**Comment by Fnyasimi** [comment]
@rkayjay Kindly use this [link](https://uchicago.box.com/s/dzwe306vq3vhar3e9rxoc4ckyxz76kd1) to access the box and download the data.

**Comment by rkayjay** [comment]
@Fnyasimi Works great now. Thank you!
