### ISSUE TITLE
adjusting for covariates twice?

### ISSUE THREAD

**Issue by rkayjay** [hakyimlab/PredictDB-Tutorial#3]
In the .Rmd, there is a section where the expression values are adjusted for the peer factors, and the resulting residual matrix ultimately used as input for the elastic net model building. It looks like the expression values are adjusted for covariates again in the  gtex_v7_nested_cv_elnet.R script lines 83-88 (called at line 222). 

Is that correct/intentional? Can you help me understand why the adjusted expression values need to be adjusted for again?

**Comment by Fnyasimi** [comment]
@rkayjay Thanks for the fine catch. The adjusting was happening twice. I have solved that and ideally if you have other covariates you need to regress out apart from the peer factors you will need to add them to the covariates file first

**Comment by rkayjay** [comment]
Wonderful. Thanks for the update!
